# Generated by Django 2.0.5 on 2018-06-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, unique=True, verbose_name='区域')),
                ('ip', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Get-IP地址')),
                ('get_threshold', models.IntegerField(blank=True, null=True, verbose_name='Get异常响应时间阈值(ms)')),
                ('post_threshold', models.IntegerField(blank=True, null=True, verbose_name='Post异常响应时间阈值(ms)')),
            ],
            options={
                'verbose_name_plural': '区域接口拨测',
            },
        ),
        migrations.CreateModel(
            name='GetReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_req_name', models.CharField(max_length=200, unique=True, verbose_name='Get请求名称')),
                ('get_path', models.CharField(max_length=500, verbose_name='请求路径')),
            ],
            options={
                'verbose_name_plural': 'Get请求',
            },
        ),
        migrations.CreateModel(
            name='PostReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_req_name', models.CharField(max_length=200, unique=True, verbose_name='Post接口名称')),
                ('post_interface_url', models.URLField(verbose_name='Post接口地址')),
                ('post_content', models.TextField(max_length=10000, verbose_name='Post内容')),
            ],
            options={
                'verbose_name_plural': 'Post请求',
            },
        ),
        migrations.AddField(
            model_name='areaurl',
            name='getreqs',
            field=models.ManyToManyField(blank=True, to='pagetest.GetReq', verbose_name='Get接口'),
        ),
        migrations.AddField(
            model_name='areaurl',
            name='postreq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagetest.PostReq', verbose_name='Post接口'),
        ),
    ]
